- name: create config directory
  file:
    path: "/tmp/{{ inventory_hostname }}"
    state: directory

- name: create config file
  copy:
    src: files/default_config
    dest: "/tmp/{{ inventory_hostname }}/config"
